### ISSUE TITLE
can not run sql in cube via jdbc

### ISSUE THREAD

**Issue by shuitao** [zsvoboda/ngods-stocks#11]
Hi, this project works fine,
but when I try to connect cube via dbeaver ( with jdbc:postgresql://localhost:3245/cube JDBC URL (username cube / password cube))
connect ok,
but we can only see database cube and schema public. no table/view can be use

**Comment by zsvoboda** [comment]
I think that this is the current limitation of the Cube driver. Still, you should be able to send SQL queries. Please take a look at this Cube.is issue https://github.com/cube-js/cube.js/pull/4831
