### ISSUE TITLE
Datahub wont start in the docker compose setup

### ISSUE THREAD

**Issue by khaferkamp** [zsvoboda/ngods-stocks#14]
Thank you very much for your hard work!
I know it is challenging to tame all the different software packages.

The standard docker-compose.yml works like a charm but with the .x86 I have the problem that I cannot get the datahub-gms container as well as elasticsearch to stay in healthy state.

I use a 8vcpu and 64 GiB machine on DigitalOcean to tinker with the setup for myself.
Is there maybe a trick to get Datahub working? This is next to Iceberg the thing I would really like to test :)

Thank you very much!

**Comment by zsvoboda** [comment]
Hi khaferkamp, I was running the Datahub on much smaller machine. However I'm not DataHub expert. I recommend you to ask on their Slack. Regards ZD
