### ISSUE TITLE
Error when re-running the workflows

### ISSUE THREAD

**Issue by varun-hopstack** [zsvoboda/ngods-stocks#3]
I get an error when re-running the workflow in dagster. For eg: Running `dbt-bronze` second time throws this error.

![image](https://user-images.githubusercontent.com/103277798/180778933-0f4d0d12-8936-438b-9a41-65ba787a1003.png)

Any thoughts?

**Comment by zsvoboda** [comment]
You must run the initialize_db before running the Spark DBT jobs because the Spark DBT doesn't drop existing tables. The e2e job starts with the initialize_db. 

LMK if it worked. 

ZD

**Comment by varun-hopstack** [comment]
@zsvoboda thanks bud! i tried that works, but what If I need to have a workflow for continuous data sync up. Is there a way to have the creation of table only during the initial run?

**Comment by zsvoboda** [comment]
Yes, you'd need to modify the DBT models. See the dbt [incremental setup](https://docs.getdbt.com/docs/building-a-dbt-project/building-models/configuring-incremental-models). The demo is configured for full loads only.

**Comment by varun-hopstack** [comment]
I configured to use incremental model, but still it fails

```
{{ config(
        materialized='incremental',
	file_format='parquet',
) }}
```

`is_incremental()` always returns False

**Comment by zsvoboda** [comment]
I suspect that you’re dropping the incremental table every time you run your job. The ‘is_incremental’ macro returns false if the target table doesn’t exist in the db. Please make sure that the incremental table isn’t dropped each run (e.g. the initialize_db drops all tables).

**Comment by varun-hopstack** [comment]
No, I am not dropping the tables every time. The table already exists error is also shown

**Comment by zsvoboda** [comment]
Hmm, then I'd recommend you to post a question to the [DBT community Slack](https://www.getdbt.com/community/join-the-community/)

**Comment by varun-hopstack** [comment]
sure, thanks!
