### ISSUE TITLE
[Question] Is iceberg a valid file format?

### ISSUE THREAD

**Issue by jaehyeon-kim** [zsvoboda/ngods-stocks#8]
Hi

I have a quick question. When I check [table configuration](https://docs.getdbt.com/reference/resource-configs/spark-configs#configuring-tables) of `dbt-spark`, `iceberg` is not found but it is used for the dbt projects. Just wondering if it works even if it is not officially supported.

Cheers,
Jaehyeon

**Comment by zsvoboda** [comment]
Yes, it does work for basic usecases (e.g. full load). I needed to tweak some dbt macros to make it work for some advanced usecases like incremental loads / merge.
